version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'monthly'
          time: '00:00'
          timezone: 'UTC'
      open-pull-requests-limit: 999
