# sudo docker compose exec cluster-m1 redis-cli -a mycluster --cluster create 127.0.0.1:7380 127.0.0.1:7381 127.0.0.1:7382 --cluster-yes

services:
  redis:
    image: redis/redis-stack-server:latest
    network_mode: host
    environment:
      - 'REDIS_ARGS=--port 6380 --requirepass myredis'
  cluster-m1:
    image: redis:latest
    network_mode: host
    command: 'redis-server --port 7380 --requirepass mycluster --cluster-enabled yes --cluster-config-file nodes.conf'
  cluster-m2:
    image: redis:latest
    network_mode: host
    command: 'redis-server --port 7381 --requirepass mycluster --cluster-enabled yes --cluster-config-file nodes.conf'
  cluster-m3:
    image: redis:latest
    network_mode: host
    command: 'redis-server --port 7382 --requirepass mycluster --cluster-enabled yes --cluster-config-file nodes.conf'
