# initialize:
# sudo docker compose exec cluster-1_master-1 redis-cli --cluster create 127.0.0.1:16380 127.0.0.1:16381 127.0.0.1:16382 --cluster-yes
# sudo docker compose exec cluster-2_master-1 redis-cli --cluster create 127.0.0.1:16480 127.0.0.1:16481 127.0.0.1:16482 --cluster-yes

services:
  cluster-1_master-1:
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_PORT_NUMBER=16380
      - REDIS_PASSWORD=cluster1
      - REDIS_NODES=cluster-1_master-1 cluster-1_master-2 cluster-1_master-3
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=0.0.0.0
      - REDISCLI_AUTH=cluster1
    network_mode: host
  cluster-1_master-2:
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_PORT_NUMBER=16381
      - REDIS_PASSWORD=cluster1
      - REDIS_NODES=cluster-1_master-1 cluster-1_master-2 cluster-1_master-3
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=0.0.0.0
    network_mode: host
  cluster-1_master-3:
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_PORT_NUMBER=16382
      - REDIS_PASSWORD=cluster1
      - REDIS_NODES=cluster-1_master-1 cluster-1_master-2 cluster-1_master-3
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=0.0.0.0
    network_mode: host
  #
  cluster-2_master-1:
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_PORT_NUMBER=16480
      - REDIS_PASSWORD=cluster2
      - REDIS_NODES=cluster-2_master-1 cluster-2_master-2 cluster-2_master-3
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=0.0.0.0
      - REDISCLI_AUTH=cluster2
    network_mode: host
  cluster-2_master-2:
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_PORT_NUMBER=16481
      - REDIS_PASSWORD=cluster2
      - REDIS_NODES=cluster-2_master-1 cluster-2_master-2 cluster-2_master-3
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=0.0.0.0
    network_mode: host
  cluster-2_master-3:
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_PORT_NUMBER=16482
      - REDIS_PASSWORD=cluster2
      - REDIS_NODES=cluster-2_master-1 cluster-2_master-2 cluster-2_master-3
      - REDIS_CLUSTER_DYNAMIC_IPS=no
      - REDIS_CLUSTER_ANNOUNCE_IP=0.0.0.0
    network_mode: host
  #
  redis-main:
    image: bitnami/redis:latest
    environment:
      - REDIS_PORT_NUMBER=6380
      - REDIS_PASSWORD=redismain
    networks:
      - dev
    ports:
      - '6380:6380'
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 32mb
  #
  redis-master:
    image: bitnami/redis:latest
    environment:
      - REDIS_PORT_NUMBER=6381
      - REDIS_PASSWORD=redismaster
      - REDIS_REPLICATION_MODE=master
      - REDIS_REPLICA_PORT=6381
    networks:
      - dev
    ports:
      - '6381:6381'
  redis-slave-1:
    image: bitnami/redis:latest
    environment:
      - REDIS_PORT_NUMBER=6480
      - REDIS_PASSWORD=redismaster
      - REDIS_REPLICATION_MODE=slave
      - REDIS_REPLICA_PORT=6480
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6381
      - REDIS_MASTER_PASSWORD=redismaster
    networks:
      - dev
    ports:
      - '6480:6480'
    depends_on:
      - redis-master
  redis-slave-2:
    image: bitnami/redis:latest
    environment:
      - REDIS_PORT_NUMBER=6481
      - REDIS_PASSWORD=redismaster
      - REDIS_REPLICATION_MODE=slave
      - REDIS_REPLICA_PORT=6481
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6381
      - REDIS_MASTER_PASSWORD=redismaster
    networks:
      - dev
    ports:
      - '6481:6481'
    depends_on:
      - redis-master
  redis-sentinel-1:
    image: bitnami/redis-sentinel:latest
    environment:
      - REDIS_SENTINEL_PORT_NUMBER=7380
      - REDIS_SENTINEL_PASSWORD=sentinel
      - REDIS_SENTINEL_RESOLVE_HOSTNAMES=yes
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6381
      - REDIS_MASTER_PASSWORD=redismaster
    networks:
      - dev
    ports:
      - '7380:7380'
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
  redis-sentinel-2:
    image: bitnami/redis-sentinel:latest
    environment:
      - REDIS_SENTINEL_PORT_NUMBER=7381
      - REDIS_SENTINEL_PASSWORD=sentinel
      - REDIS_SENTINEL_RESOLVE_HOSTNAMES=yes
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6381
      - REDIS_MASTER_PASSWORD=redismaster
    networks:
      - dev
    ports:
      - '7381:7381'
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
networks:
  dev:
