# Initialize clusters:
# sudo docker compose exec cluster-1-master-1 redis-cli --cluster create 127.0.0.1:16380 127.0.0.1:16381 127.0.0.1:16382 --cluster-yes
# sudo docker compose exec cluster-2-master-1 redis-cli --cluster create 127.0.0.1:16480 127.0.0.1:16481 127.0.0.1:16482 --cluster-yes

version: '3.9'
networks:
    testing:
        driver: bridge
services:
    cluster-1-master-1:
        image: bitnami/redis-cluster:latest
        environment:
            - REDIS_PORT_NUMBER=16380
            - REDIS_PASSWORD=cluster1
            - REDIS_NODES=cluster-1-master-1 cluster-1-master-2 cluster-1-master-3
            - REDIS_CLUSTER_DYNAMIC_IPS=no
            - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1
            - REDISCLI_AUTH=cluster1
        network_mode: host
        command: /opt/bitnami/scripts/redis-cluster/run.sh --maxmemory 100mb
    cluster-1-master-2:
        image: bitnami/redis-cluster:latest
        environment:
            - REDIS_PORT_NUMBER=16381
            - REDIS_PASSWORD=cluster1
            - REDIS_NODES=cluster-1-master-1 cluster-1-master-2 cluster-1-master-3
            - REDIS_CLUSTER_DYNAMIC_IPS=no
            - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1
        network_mode: host
        command: /opt/bitnami/scripts/redis-cluster/run.sh --maxmemory 100mb
    cluster-1-master-3:
        image: bitnami/redis-cluster:latest
        environment:
            - REDIS_PORT_NUMBER=16382
            - REDIS_PASSWORD=cluster1
            - REDIS_NODES=cluster-1-master-1 cluster-1-master-2 cluster-1-master-3
            - REDIS_CLUSTER_DYNAMIC_IPS=no
            - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1
        network_mode: host
        command: /opt/bitnami/scripts/redis-cluster/run.sh --maxmemory 100mb
    # ████████╗░██████╗
    # ╚══██╔══╝██╔════╝
    # ░░░██║░░░╚█████╗░
    # ░░░██║░░░░╚═══██╗
    # ░░░██║░░░██████╔╝
    # ░░░╚═╝░░░╚═════╝░
    cluster-2-master-1:
        image: bitnami/redis-cluster:latest
        environment:
            - REDIS_PORT_NUMBER=16480
            - REDIS_PASSWORD=cluster2
            - REDIS_NODES=cluster-2-master-1 cluster-2-master-2 cluster-2-master-3
            - REDIS_CLUSTER_DYNAMIC_IPS=no
            - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1
            - REDISCLI_AUTH=cluster2
        network_mode: host
        command: /opt/bitnami/scripts/redis-cluster/run.sh --maxmemory 100mb
    cluster-2-master-2:
        image: bitnami/redis-cluster:latest
        environment:
            - REDIS_PORT_NUMBER=16481
            - REDIS_PASSWORD=cluster2
            - REDIS_NODES=cluster-2-master-1 cluster-2-master-2 cluster-2-master-3
            - REDIS_CLUSTER_DYNAMIC_IPS=no
            - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1
        network_mode: host
        command: /opt/bitnami/scripts/redis-cluster/run.sh --maxmemory 100mb
    cluster-2-master-3:
        image: bitnami/redis-cluster:latest
        environment:
            - REDIS_PORT_NUMBER=16482
            - REDIS_PASSWORD=cluster2
            - REDIS_NODES=cluster-2-master-1 cluster-2-master-2 cluster-2-master-3
            - REDIS_CLUSTER_DYNAMIC_IPS=no
            - REDIS_CLUSTER_ANNOUNCE_IP=127.0.0.1
        network_mode: host
        command: /opt/bitnami/scripts/redis-cluster/run.sh --maxmemory 100mb
    # ████████╗░██████╗
    # ╚══██╔══╝██╔════╝
    # ░░░██║░░░╚█████╗░
    # ░░░██║░░░░╚═══██╗
    # ░░░██║░░░██████╔╝
    # ░░░╚═╝░░░╚═════╝░
    redis-main:
        image: bitnami/redis:latest
        environment:
            - REDIS_PORT_NUMBER=6380
            - REDIS_PASSWORD=redismain
        networks:
            - testing
        ports:
            - '127.0.0.1:6380:6380'
        command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb
    # ████████╗░██████╗
    # ╚══██╔══╝██╔════╝
    # ░░░██║░░░╚█████╗░
    # ░░░██║░░░░╚═══██╗
    # ░░░██║░░░██████╔╝
    # ░░░╚═╝░░░╚═════╝░
    redis-master:
        image: bitnami/redis:latest
        environment:
            - REDIS_PORT_NUMBER=6381
            - REDIS_PASSWORD=redismaster
            - REDIS_REPLICATION_MODE=master
            - REDIS_REPLICA_PORT=6381
        networks:
            - testing
        ports:
            - '127.0.0.1:6381:6381'
        command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb
    redis-slave-1:
        image: bitnami/redis:latest
        environment:
            - REDIS_PORT_NUMBER=6480
            - REDIS_PASSWORD=redismaster
            - REDIS_REPLICATION_MODE=slave
            - REDIS_REPLICA_PORT=6480
            - REDIS_MASTER_HOST=redis-master
            - REDIS_MASTER_PORT_NUMBER=6381
            - REDIS_MASTER_PASSWORD=redismaster
        networks:
            - testing
        ports:
            - '127.0.0.1:6480:6480'
        depends_on:
            - redis-master
    redis-slave-2:
        image: bitnami/redis:latest
        environment:
            - REDIS_PORT_NUMBER=6481
            - REDIS_PASSWORD=redismaster
            - REDIS_REPLICATION_MODE=slave
            - REDIS_REPLICA_PORT=6481
            - REDIS_MASTER_HOST=redis-master
            - REDIS_MASTER_PORT_NUMBER=6381
            - REDIS_MASTER_PASSWORD=redismaster
        networks:
            - testing
        ports:
            - '127.0.0.1:6481:6481'
        depends_on:
            - redis-master
    redis-sentinel-1:
        image: bitnami/redis-sentinel:latest
        environment:
            - REDIS_SENTINEL_PORT_NUMBER=7380
            - REDIS_SENTINEL_PASSWORD=sentinel
            - REDIS_SENTINEL_QUORUM=2
            - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
            - REDIS_SENTINEL_FAILOVER_TIMEOUT=5000
            - REDIS_SENTINEL_RESOLVE_HOSTNAMES=yes
            - REDIS_MASTER_HOST=redis-master
            - REDIS_MASTER_PORT_NUMBER=6381
            - REDIS_MASTER_PASSWORD=redismaster
        networks:
            - testing
        ports:
            - '127.0.0.1:7380:7380'
        depends_on:
            - redis-master
            - redis-slave-1
            - redis-slave-2
    redis-sentinel-2:
        image: bitnami/redis-sentinel:latest
        environment:
            - REDIS_SENTINEL_PORT_NUMBER=7381
            - REDIS_SENTINEL_PASSWORD=sentinel
            - REDIS_SENTINEL_QUORUM=2
            - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
            - REDIS_SENTINEL_FAILOVER_TIMEOUT=5000
            - REDIS_SENTINEL_RESOLVE_HOSTNAMES=yes
            - REDIS_MASTER_HOST=redis-master
            - REDIS_MASTER_PORT_NUMBER=6381
            - REDIS_MASTER_PASSWORD=redismaster
        networks:
            - testing
        ports:
            - '127.0.0.1:7381:7381'
        depends_on:
            - redis-master
            - redis-slave-1
            - redis-slave-2
