name: "\U0001F41B Bug Report"
description: "If something isn't working as expected \U0001F914"
body:
    - type: markdown
      attributes:
          value: |
              ## :warning: We use GitHub Issues to track bug reports and feature requests

              If you are not sure that your issue is a bug, you could:

              - read the [ioredis documentation](https://github.com/luin/ioredis) page
              - read the [Redis Documentation](https://redis.io/documentation) page
              - read the [Redis Replication](https://redis.io/topics/replication) page
              - read the [Redis Sentinel](https://redis.io/topics/sentinel) page
              - read the [Redis Cluster](https://redis.io/topics/cluster-tutorial), [Specification](https://redis.io/topics/cluster-spec) page

              **NOTE:** You don't need to answer questions that you know that aren't relevant.

              ---

    - type: textarea
      validations:
          required: true
      attributes:
          label: 'Current behavior'
          description: 'How the issue manifests?'

    - type: input
      validations:
          required: true
      attributes:
          label: 'Minimum reproduction code'
          description: '[Wtf is a minimum reproduction?](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction)'
          placeholder: 'https://github.com/...'

    - type: textarea
      attributes:
          label: 'Steps to reproduce'
          description: |
              How the issue manifests?
              You could leave this blank if you already write this in your reproduction code
          placeholder: |
              1. `npm ci`
              2. `npm start:dev`
              3. See error...

    - type: textarea
      validations:
          required: true
      attributes:
          label: 'Expected behavior'
          description: 'A clear and concise description of what you expected to happend (or code)'

    - type: markdown
      attributes:
          value: |
              ---

    - type: input
      attributes:
          label: 'NestJS version'
          description: |
              Which version of `@nestjs/core` are you using?
              **Tip**: Make sure that all of yours `@nestjs/*` dependencies are in sync!
          placeholder: '8.1.3'

    - type: textarea
      validations:
          required: true
      attributes:
          label: 'Packages versions'
          description: |
              You could leave your whole `package.json` dependencies list here, or just indicate which version of `@nestjs/*` you are using
              **Tip**: run _npx nest info_
          value: |
              ```json

              ```

    - type: input
      attributes:
          label: 'Node.js version'
          description: 'Which version of Node.js are you using?'
          placeholder: '14.17.6'

    - type: checkboxes
      validations:
          required: true
      attributes:
          label: 'In which operating systems have you tested?'
          options:
              - label: macOS
              - label: Windows
              - label: Linux

    - type: markdown
      attributes:
          value: |
              ---

    - type: textarea
      attributes:
          label: 'Other'
          description: |
              Anything else relevant? eg: Logs, OS version, IDE, package manager, etc.
              **Tip:** You can attach images, recordings or log files by clicking this area to highlight it and then dragging files in
