name: Publish
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
          architecture: x64
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install --frozen-lockfile
      - run: pnpm -F "@liaoliaots/nestjs-redis" run lint
      - name: Build for CJS
        run: pnpm -F "@liaoliaots/nestjs-redis" run build
      - name: Build for ESM
        run: |
          npm pkg set type=module
          pnpm -F "@liaoliaots/nestjs-redis" exec tsc --project tsconfig.esm.json && tsc-alias -p tsconfig.esm.json
      # - run: pnpm -r run publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
