name: release
on: workflow_dispatch
jobs:
    release:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  architecture: 'x64'
                  cache: 'npm'
                  check-latest: true
                  registry-url: 'https://registry.npmjs.org'
            - run: npm install -g npm@latest
            - run: npm ci
            - run: npm run lint
            - run: npm run build
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
