name: Release
on: workflow_dispatch
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  check-latest: true
                  registry-url: https://registry.npmjs.org
            - name: Update npm
              run: npm install -g npm@latest -verbose
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Publish to npm
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - uses: actions/setup-node@v2
              with:
                  node-version: '14'
                  check-latest: true
                  registry-url: https://npm.pkg.github.com
            - name: Update npm
              run: npm install -g npm@latest -verbose
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Publish to GitHub Packages
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
