name: testing
on:
  pull_request:
    branches:
      - main
jobs:
  unit_e2e:
    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        node_version:
          - 12.22.12
          - 14.20.0
          - 16.16.0
        architecture:
          - x64
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          cache: pnpm
      - run: pnpm install
      - run: docker-compose up -d
      - run: docker-compose exec -T cluster-1_master-1 redis-cli --cluster create 127.0.0.1:16380 127.0.0.1:16381 127.0.0.1:16382 --cluster-yes
      - run: docker-compose exec -T cluster-2_master-1 redis-cli --cluster create 127.0.0.1:16480 127.0.0.1:16481 127.0.0.1:16482 --cluster-yes
      - run: pnpm --filter @liaoliaots/nestjs-redis lint:es
      - run: pnpm --filter @liaoliaots/nestjs-redis lint:tsc
      - run: pnpm --filter @liaoliaots/nestjs-redis test
      - run: pnpm --filter @liaoliaots/nestjs-redis test:e2e
      - run: docker-compose down -v
